[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
trailingSlash = true

[[plugins]]
package = "netlify-plugin-submit-sitemap"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[build]
command = "astro build"
publish = "dist"
